# Generated by Django 6.0.5 on 2026-05-29 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('territories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('presidential', 'Presidential'), ('legislative', 'Legislative'), ('local_apc', 'Local (APC)'), ('local_apw', 'Local (APW)'), ('referendum', 'Referendum')], max_length=20)),
                ('election_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BureauDeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('registered_voters', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bureaux', to='territories.commune')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bureaux', to='elections.election')),
            ],
            options={
                'verbose_name_plural': 'Bureaux de Vote',
                'unique_together': {('commune', 'election', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ElectionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255)),
                ('is_our_party', models.BooleanField(default=False, help_text='Check ONLY for MSP')),
                ('display_order', models.SmallIntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='elections.election')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('election', 'display_order')},
            },
        ),
        migrations.CreateModel(
            name='StationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_voters', models.IntegerField()),
                ('total_votes_cast', models.IntegerField()),
                ('null_votes', models.IntegerField(default=0)),
                ('blank_votes', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('bureau', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='result', to='elections.bureaudevote')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='elections.election')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_results', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('election_list', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='elections.electionlist')),
                ('station_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_results', to='elections.stationresult')),
            ],
            options={
                'unique_together': {('station_result', 'election_list')},
            },
        ),
    ]
