# Generated by Django 6.0.5 on 2026-05-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureaudevote',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bureaudevote',
            name='registered_voters',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
