# Generated by Django 6.0.5 on 2026-05-29 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_bureaudevote_name_and_more'),
        ('territories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bureaudevote',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stationresult',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='bureaudevote',
            index=models.Index(fields=['is_deleted'], name='elections_b_is_dele_922716_idx'),
        ),
        migrations.AddIndex(
            model_name='stationresult',
            index=models.Index(fields=['is_deleted'], name='elections_s_is_dele_1af379_idx'),
        ),
    ]
