# Generated by Django 6.0.5 on 2026-06-14 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_resultauditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bureaudevote',
            options={'verbose_name': 'مركز تصويت', 'verbose_name_plural': 'محاضر التصويت'},
        ),
    ]
