# Generated by Django 6.0.5 on 2026-06-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_alter_bureaudevote_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electionlist',
            options={'ordering': ['display_order'], 'verbose_name': 'قائمة انتخابية', 'verbose_name_plural': 'القوائم الانتخابية'},
        ),
        migrations.AlterUniqueTogether(
            name='electionlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='election',
            name='total_seats',
            field=models.IntegerField(default=4, help_text='عدد المقاعد المتنافس عليها في هذا الانتخاب', verbose_name='عدد المقاعد المخصصة'),
        ),
        migrations.AlterField(
            model_name='electionlist',
            name='display_order',
            field=models.SmallIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='electionlist',
            name='is_our_party',
            field=models.BooleanField(default=False, help_text='Check ONLY for MSP', verbose_name='هل هي قائمة الحركة (MSP)؟'),
        ),
        migrations.AlterField(
            model_name='electionlist',
            name='name_ar',
            field=models.CharField(max_length=255, verbose_name='اسم القائمة / الحزب'),
        ),
        migrations.AlterField(
            model_name='electionlist',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم القائمة (فرنسي) - اختياري'),
        ),
        migrations.AlterUniqueTogether(
            name='electionlist',
            unique_together={('election', 'name_ar')},
        ),
    ]
