# Generated by Django 6.0.5 on 2026-06-14 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_alter_electionlist_options_and_more'),
        ('territories', '0002_wilaya_total_seats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electionlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='electionlist',
            name='wilaya',
            field=models.ForeignKey(blank=True, help_text='اتركه فارغاً إذا كانت قائمة وطنية / حزب رسمي', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_lists', to='territories.wilaya', verbose_name='الولاية (للقوائم الحرة فقط)'),
        ),
        migrations.AlterUniqueTogether(
            name='electionlist',
            unique_together={('election', 'name_ar', 'wilaya')},
        ),
    ]
