# Generated by Django 6.0.5 on 2026-06-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_alter_electionlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionlist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط (يظهر في الاستمارات)'),
        ),
    ]
