# Generated by Django 6.0.5 on 2026-06-18 00:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_electionlist_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultauditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'سجل تدقيق', 'verbose_name_plural': 'سجلات التدقيق'},
        ),
        migrations.RemoveField(
            model_name='resultauditlog',
            name='changed_at',
        ),
        migrations.AddField(
            model_name='resultauditlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='الوقت'),
        ),
        migrations.AlterField(
            model_name='resultauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'إضافة'), ('update', 'تعديل'), ('delete', 'حذف')], max_length=10, verbose_name='العملية'),
        ),
        migrations.AlterField(
            model_name='resultauditlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='resultauditlog',
            name='new_values',
            field=models.JSONField(blank=True, null=True, verbose_name='القيم الجديدة'),
        ),
        migrations.AlterField(
            model_name='resultauditlog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='resultauditlog',
            name='old_values',
            field=models.JSONField(blank=True, null=True, verbose_name='القيم القديمة'),
        ),
        migrations.AlterField(
            model_name='resultauditlog',
            name='record_id',
            field=models.CharField(max_length=50, verbose_name='رقم السجل'),
        ),
        migrations.AlterField(
            model_name='resultauditlog',
            name='table_name',
            field=models.CharField(max_length=100, verbose_name='الجدول'),
        ),
    ]
