# Generated by Django 6.0.5 on 2026-06-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_alter_resultauditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultauditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='الوقت'),
        ),
    ]
