# Generated by Django 6.0.5 on 2026-06-19 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0010_alter_resultauditlog_timestamp'),
        ('territories', '0002_wilaya_total_seats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bureaudevote',
            name='elections_b_is_dele_922716_idx',
        ),
        migrations.RemoveIndex(
            model_name='stationresult',
            name='elections_s_is_dele_1af379_idx',
        ),
        migrations.AddIndex(
            model_name='bureaudevote',
            index=models.Index(fields=['is_deleted', 'election'], name='elections_b_is_dele_c12b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='bureaudevote',
            index=models.Index(fields=['commune', 'is_deleted'], name='elections_b_commune_3d4188_idx'),
        ),
        migrations.AddIndex(
            model_name='bureaudevote',
            index=models.Index(fields=['code'], name='elections_b_code_6b4342_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['status', '-election_date'], name='elections_e_status_d649bb_idx'),
        ),
        migrations.AddIndex(
            model_name='electionlist',
            index=models.Index(fields=['election', 'is_our_party'], name='elections_e_electio_70cd01_idx'),
        ),
        migrations.AddIndex(
            model_name='listresult',
            index=models.Index(fields=['station_result', 'election_list'], name='elections_l_station_71bb2c_idx'),
        ),
        migrations.AddIndex(
            model_name='resultauditlog',
            index=models.Index(fields=['-timestamp'], name='elections_r_timesta_7ff2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='resultauditlog',
            index=models.Index(fields=['action'], name='elections_r_action_72839c_idx'),
        ),
        migrations.AddIndex(
            model_name='resultauditlog',
            index=models.Index(fields=['table_name'], name='elections_r_table_n_9bb2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='stationresult',
            index=models.Index(fields=['bureau', 'is_deleted'], name='elections_s_bureau__3859ad_idx'),
        ),
        migrations.AddIndex(
            model_name='stationresult',
            index=models.Index(fields=['election', 'is_deleted'], name='elections_s_electio_251a16_idx'),
        ),
        migrations.AddIndex(
            model_name='stationresult',
            index=models.Index(fields=['-submitted_at'], name='elections_s_submitt_75acda_idx'),
        ),
    ]
