# Generated by Django 6.0.5 on 2026-05-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code (e.g., 16001)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (AR)')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Name (FR)')),
            ],
            options={
                'ordering': ['wilaya__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField(unique=True, verbose_name='Code (01-69)')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (AR)')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Name (FR)')),
            ],
            options={
                'verbose_name_plural': 'Wilayas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CommuneSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_bureau_creation', models.BooleanField(default=False)),
                ('commune', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='territories.commune')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='communes', to='territories.wilaya'),
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together={('wilaya', 'code')},
        ),
    ]
