# Generated by Django 6.0.5 on 2026-06-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilaya',
            name='total_seats',
            field=models.IntegerField(default=4, verbose_name='عدد المقاعد المخصصة'),
        ),
    ]
